### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by coolmian** [siutin/stable-diffusion-webui-docker#11]
command:
```shell
docker run -it --name sdw --gpus all --network host  -v $(pwd)/models:/app/stable-diffusion-webui/models -v $(pwd)/outputs:/app/stable-diffusion-webui/outputs  --rm siutin/stable-diffusion-webui-docker:cuda-v1.6.0-2023-09-02   bash webui.sh --share
```

log:
```
################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on sduser user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc_minimal.so.4
Python 3.10.7 (main, May 29 2023, 13:51:48) [GCC 12.2.0]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Traceback (most recent call last):
  File "/app/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/app/stable-diffusion-webui/launch.py", line 39, in main
    prepare_environment()
  File "/app/stable-diffusion-webui/modules/launch_utils.py", line 356, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
```

In order to obtain detailed errors, I entered the container to execute
```
source venv/bin/activate
python -c "import torch;torch.tensor(1).cuda()"
```

show log:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 304: OS call failed or operation not supported on this OS
```

Physical machine information:
```
GPU 0: NVIDIA GeForce RTX 2080 Ti 
GPU 1: NVIDIA GeForce RTX 2080 Ti 
GPU 2: NVIDIA GeForce RTX 2080 Ti 
GPU 3: NVIDIA GeForce RTX 2080 Ti

Driver Version: 535.86.10    CUDA Version: 12.2
OS: Ubuntu 22.04.1 LTS
Docker version 19.03.15, build 99e3ed8919
```

**Comment by siutin** [comment]
My bad! but it's fixed now. Feel free to rebuild your image.
