### ISSUE TITLE
training not running after installing the Dreambooth extension

### ISSUE THREAD

**Issue by mozily** [siutin/stable-diffusion-webui-docker#23]
this method worked well until 2024-10-22, but it suddenly stopped working after that.

image : siutin/stable-diffusion-webui-docker:latest-cuda
command : --listen --enable-insecure-extension-access

Until then, I was using it well, but suddenly when I run the train in Dreambooth, it outputs the following error.

--------------------------------------------------------------------------------------------------------
Initializing dreambooth training...
Traceback (most recent call last):
  File "/app/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 732, in start_training
    from dreambooth.train_dreambooth import main  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 34, in <module>
    from diffusers.training_utils import unet_lora_state_dict
  File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/diffusers/training_utils.py", line 27, in <module>
    if transformers.integrations.deepspeed.is_deepspeed_zero3_enabled():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'transformers.integrations' has no attribute 'deepspeed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 734, in start_training
    from dreambooth.train_dreambooth import main  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 34, in <module>
    from diffusers.training_utils import unet_lora_state_dict
  File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/diffusers/training_utils.py", line 27, in <module>
    if transformers.integrations.deepspeed.is_deepspeed_zero3_enabled():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'transformers.integrations' has no attribute 'deepspeed'
Duration: 00:00:00
Duration: 00:00:01
--------------------------------------------------------------------------------------------------------

Please help me understand why this error is occurring.

**Comment by siutin** [comment]
Sorry to hear about that, currently there have been changes in the way releases are related to the CUDA version. Previously, each release was tied to CUDA version 12.1.1. Could you try using this to see if it works?

image: siutin/stable-diffusion-webui-docker:latest-cuda-12.1.1

**Comment by mozily** [comment]
@siutin hank you for the quick response.

I tried again using the "latest-cuda-12.1.1" image you mentioned, but the same error as in the main text is displayed.

The last image I successfully used was the "latest-cuda" image from 2024-10-22. With the same image, I was able to recreate the container, install DreamBooth, and even build the model. However, when I attempt to train it afterward, the same error as above is displayed.
